id: A4F95E9CC
title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as Ornaments
  of the Practice Lineage'
type: translation
pechas:
- I2A7CE255
- I526B09E3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:36:07.891970
  last_modified_at: 2023-01-04 12:36:07.891986
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I2A7CE255/6148: AE65
  I526B09E3/60A3: AE65
